@echo off
IF EXIST "../synth/__projnav" rmdir /S /Q "../synth/__projnav" 
IF EXIST "../synth/xst" rmdir /S /Q "../synth/xst" 
IF EXIST "../synth/_ngo" rmdir /S /Q "../synth/_ngo" 

IF EXIST _xmsgs rmdir /S /Q _xmsgs
IF EXIST icon_xdb rmdir /S /Q icon_xdb
IF EXIST ila_xdb rmdir /S /Q ila_xdb
IF EXIST tmp rmdir /S /Q tmp
IF EXIST vio_xdb rmdir /S /Q vio_xdb
IF EXIST xlnx_auto_0_xdb rmdir /S /Q xlnx_auto_0_xdb

IF EXIST coregen.cgp del /F /Q coregen.cgp
IF EXIST coregen.cgc del /F /Q coregen.cgc
IF EXIST coregen.log del /F /Q coregen.log
IF EXIST icon.asy del /F /Q icon.asy
IF EXIST icon.gise del /F /Q icon.gise
IF EXIST icon.ise del /F /Q icon.ise
IF EXIST icon.ngc del /F /Q icon.ngc
IF EXIST icon.xco del /F /Q icon.xco
IF EXIST icon.xise del /F /Q icon.xise
IF EXIST icon_flist.txt del /F /Q icon_flist.txt
IF EXIST icon_readme.txt del /F /Q icon_readme.txt
IF EXIST icon_xmdf.tcl del /F /Q icon_xmdf.tcl

IF EXIST ila.cdc del /F /Q ila.cdc
IF EXIST ila.gise del /F /Q ila.gise
IF EXIST ila.ise del /F /Q ila.ise
IF EXIST ila.ngc del /F /Q ila.ngc
IF EXIST ila.xco del /F /Q ila.xco
IF EXIST ila.xise del /F /Q ila.xise
IF EXIST ila_flist.txt del /F /Q ila_flist.txt
IF EXIST ila_readme.txt del /F /Q ila_readme.txt
IF EXIST ila_xmdf.tcl del /F /Q ila_xmdf.tcl

IF EXIST vio.cdc del /F /Q vio.cdc
IF EXIST vio.gise del /F /Q vio.gise
IF EXIST vio.ise del /F /Q vio.ise
IF EXIST vio.ngc del /F /Q vio.ngc
IF EXIST vio.xco del /F /Q vio.xco
IF EXIST vio.xise del /F /Q vio.xise
IF EXIST vio_flist.txt del /F /Q vio_flist.txt
IF EXIST vio_readme.txt del /F /Q vio_readme.txt
IF EXIST vio_xmdf.tcl del /F /Q vio_xmdf.tcl


IF EXIST ise_flow_results.txt del /F /Q ise_flow_results.txt
IF EXIST mem_interface_top.syr del /F /Q mem_interface_top.syr
IF EXIST smartpreview.twr del /F /Q  smartpreview.twr

IF EXIST ddr_ctrl.bgn del /F /Q  ddr_ctrl.bgn
IF EXIST ddr_ctrl_bitgen.xwbt del /F /Q  ddr_ctrl_bitgen.xwbt
IF EXIST ddr_ctrl.bit del /F /Q  ddr_ctrl.bit
IF EXIST ddr_ctrl.bld del /F /Q ddr_ctrl.bld
IF EXIST ddr_ctrl.drc del /F /Q  ddr_ctrl.drc
IF EXIST ddr_ctrl.ncd del /F /Q  ddr_ctrl.ncd
IF EXIST ddr_ctrl.ngc del /F /Q ddr_ctrl.ngc
IF EXIST ddr_ctrl_prev_built.ngd del /F /Q ddr_ctrl_prev_built.ngd
IF EXIST ddr_ctrl.ngd del /F /Q ddr_ctrl.ngd
IF EXIST ddr_ctrl.ngr del /F /Q ddr_ctrl.ngr
IF EXIST ddr_ctrl.pad del /F /Q  ddr_ctrl.pad
IF EXIST ddr_ctrl.par del /F /Q  ddr_ctrl.par
IF EXIST ddr_ctrl.pcf del /F /Q  ddr_ctrl.pcf
IF EXIST ddr_ctrl.ptwx del /F /Q  ddr_ctrl.ptwx
IF EXIST ddr_ctrl.twr del /F /Q  ddr_ctrl.twr
IF EXIST ddr_ctrl.twx del /F /Q  ddr_ctrl.twx
IF EXIST ddr_ctrl.unroutes del /F /Q  ddr_ctrl.unroutes
IF EXIST ddr_ctrl.ut del /F /Q  ddr_ctrl.ut
IF EXIST ddr_ctrl.xpi del /F /Q  ddr_ctrl.xpi
IF EXIST ddr_ctrl_map.map del /F /Q  ddr_ctrl_map.map
IF EXIST ddr_ctrl_map.mrp del /F /Q  ddr_ctrl_map.mrp
IF EXIST ddr_ctrl_map.ncd del /F /Q  ddr_ctrl_map.ncd
IF EXIST ddr_ctrl_map.ngm del /F /Q  ddr_ctrl_map.ngm
IF EXIST ddr_ctrl_map.xrpt del /F /Q  ddr_ctrl_map.xrpt
IF EXIST ddr_ctrl_ngdbuild.xrpt del /F /Q  ddr_ctrl_ngdbuild.xrpt
IF EXIST ddr_ctrl_pad.csv del /F /Q  ddr_ctrl_pad.csv
IF EXIST ddr_ctrl_pad.txt del /F /Q  ddr_ctrl_pad.txt
IF EXIST ddr_ctrl_par.xrpt del /F /Q  ddr_ctrl_par.xrpt
IF EXIST ddr_ctrl_summary.xml del /F /Q  ddr_ctrl_summary.xml
IF EXIST ddr_ctrl_usage.xml del /F /Q  ddr_ctrl_usage.xml
IF EXIST ddr_ctrl_vhdl.prj del /F /Q ddr_ctrl_vhdl.prj
IF EXIST ddr_ctrl_xst.xrpt del /F /Q ddr_ctrl_xst.xrpt

:: Files and folders generated by create ise
IF EXIST xst rmdir /S /Q xst 
IF EXIST _ngo rmdir /S /Q _ngo
IF EXIST test_xdb rmdir /S /Q test_xdb 
IF EXIST _xmsgs rmdir /S /Q _xmsgs 
IF EXIST test.ntrc_log del /F /Q test.ntrc_log
If EXIST ddr_ctrl.cmd_log del /F /Q ddr_ctrl.cmd_log
IF EXIST ddr_ctrl.lso del /F /Q  ddr_ctrl.lso
IF EXIST ddr_ctrl.ngc del /F /Q ddr_ctrl.ngc
IF EXIST ddr_ctrl.prj del /F /Q  ddr_ctrl.prj
IF EXIST ddr_ctrl.stx del /F /Q ddr_ctrl.stx
IF EXIST ddr_ctrl.syr del /F /Q ddr_ctrl.syr
IF EXIST ddr_ctrl.xst del /F /Q ddr_ctrl.xst
IF EXIST ddr_ctrl_summary.html del /F /Q  ddr_ctrl_summary.html
IF EXIST ddr_ctrl_usage.html del /F /Q  ddr_ctrl_usage.html
IF EXIST ddr_ctrl_prev_built.xst del /F /Q ddr_ctrl_prev_built.xst
IF EXIST ddr_ctrl_summary.xst del /F /Q ddr_ctrl_summary.xst
IF EXIST par_usage_statistics.html del /F /Q par_usage_statistics.html
IF EXIST usage_statistics_webtalk.html del /F /Q usage_statistics_webtalk.html
IF EXIST webtalk.log del /F /Q webtalk.log
IF EXIST device_usage_statistics.html del /F /Q	device_usage_statistics.html
IF EXIST ddr_ctrl_guide.ncd del /F /Q  ddr_ctrl_guide.ncd
IF EXIST test.gise del /F /Q test.gise
IF EXIST test.xise del /F /Q test.xise
IF EXIST test.xise del /F /Q test.xise

@echo on
