######################################################################
##
## Filename: ddr_tester_s3a_tb.udo
## Created on: Sun Jul 03 6:15:14 рм GTB Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
