######################################################################
##
## Filename: sim_tb_top.udo
## Created on: Mon Jul 04 10:48:00 μμ GTB Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
