######################################################################
##
## Filename: ddr_tester_s3e_tb.udo
## Created on: Sat Jun 04 08:19:24 PM EEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
